server:
  port: 8080
spring:
  application:
    name: makeline-service
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
dapr:
  pubsub:
    name: pubsub-servicebus
    topic: orders
    subscription: makeline-service
  statestore:
    name: statestore-redis
logging:
  level:
    com.dapraca: INFO
